+function($){
  $(document).ready(function(){
    $('#login-form').validate({
      rules:{
        username:{
          required:true
        },
        password:{
          required:true
        }
      },
      errorClass:'error',
      validClass:'success',
      highlight:function(element){
        $(element).parent().addClass('highlight-error').removeClass('highlight-success');
      },
      unhighlight:function(element){
        $(element).parent().removeClass('highlight-error').addClass('highlight-success');
      },
      errorPlacement:function(error,element){
          error.insertAfter(element.parent());
      }
    });
  });
}(jQuery);