+function($){
  $(document).ready(function(){
    $('#signin-form').validate({
      rules:{
        username:{
          required:true
        },
        email:{
          required:true,
          email:true
        },
        password:{
          required:true
        },
        comfirmPassword:{
          required:true,
          equalTo:".password"
        }
      },
      messages:{
        comfirmPassword:{
          equalTo:"密码输入不一致，请重新输入。"
        }
      },
      errorClass:'error',
      validClass:'success',
      highlight:function(element){
        $(element).addClass('highlight-error').removeClass('highlight-success');
      },
      unhighlight:function(element){
        $(element).removeClass('highlight-error').addClass('highlight-success');
      },
      errorPlacement:function(error,element){
        error.insertAfter(element.parent());
      }
    });
  });
}(jQuery);